version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gestao_escolar
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432" # Expõe a porta para conexão local, se necessário
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d gestao_escolar"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: gestao_escolar_api
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/gestao_escolar
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: